name: clinique_doctor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^9.2.0
  geocoding: ^2.0.1
  geolocator: ^8.2.0
  get: ^4.6.1
  google_maps_flutter: ^2.1.1
  gradient_widgets: ^0.6.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  lint: ^1.8.1
  lottie: ^1.1.0
  path_provider: ^2.0.7
  shared_preferences: ^2.0.13
  splashscreen: null
  styled_widget: ^0.4.0+3
  syncfusion_flutter_calendar: ^19.4.43

dev_dependencies:
  cloud_firestore: ^3.1.8
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.10.0
  firebase_database: ^9.0.6
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
