name: clinique_doctor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.0
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^9.2.0
  geocoding: ^2.0.1
  geolocator: 7.0.3
  get: ^4.6.1
  google_maps_flutter: ^2.1.1
  gradient_widgets: ^0.6.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  lottie: ^1.1.0
  path_provider: ^2.0.7
  shared_preferences: 2.0.6
  splashscreen: null

dev_dependencies:
  cloud_firestore: 2.3.0
  firebase_analytics: 8.1.2
  firebase_auth: 2.0.0
  firebase_core: ^1.10.0
  firebase_database: 7.1.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
